import streamlit as st
import pandas as pd


# -----------------------------------------------------------------------------
# 1. Page Setup & Data Extraction
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title='Electricity Demand Analytics & Forecasting',
    layout='wide',
    initial_sidebar_state='collapsed'
)

st.title('US Electricity Demand Analytics Dashboard')
st.divider()

# Data extraction
@st.cache_data
def load_data(path):
    df = pd.read_csv(path)
    df['time_stamp'] = pd.to_datetime(df['time_stamp'])
    return df

try:
    df = load_data('https://raw.githubusercontent.com/comradelouis-ftj/US_RTO_Electricity_Demand_Dashboard_and_Forecasting/refs/heads/master/data_processing/data/demand_electricty_generation_mlready.csv')
except:
    st.error('Data not found, try again later')
    st.stop()

# -----------------------------------------------------------------------------
# 2. RTO/Datetime Selection
# -----------------------------------------------------------------------------
max_time = df['time_stamp'].max()
min_time = df['time_stamp'].min()
with st.form('RTO & Datetime Selection'):
    start_default = (max_time - pd.Timedelta(hours=72)).date()
    default_end = max_time.date()

    col1, col2 = st.columns([1, 1,])
    with col1:
        rto = st.selectbox(
            'Select RTO', 
            options=df['rto_full_name'].unique(),
            index=0
        )
    with col2:
        time_interval = st.date_input(
            'Select Date interval',
            value=(start_default, default_end),
            min_value=min_time.date(),
            max_value=max_time.date()
        )

    show = st.form_submit_button('Show Analytics', use_container_width=True)

st.divider()

# -----------------------------------------------------------------------------
# 3. Showing Analytics
# -----------------------------------------------------------------------------
if not show:
    st.info('💡 Select RTO (Regional Transmission Organization) and date interval, then click **Show Analytics** to show analytics')
else:
    if isinstance(time_interval, tuple) and len(time_interval) == 2:
        start_date, end_date = time_interval
    else:
        start_date = end_date = time_interval

    df_filtered = df[
        (df['rto_full_name']==rto) & (df['time_stamp'].dt.date>=start_date) & (df['time_stamp'].dt.date<=end_date)
    ].sort_values(by='time_stamp')
    df_filtered_chart = df_filtered.set_index('time_stamp')

    if df_filtered_chart.empty:
        st.warning('For the spcific RTO & timestamp, the data is empty. Try again with another RTO & time interval')
    else:
        # -----------------------------------------------------------------------------
        # RTO DEMAND
        # -----------------------------------------------------------------------------
        with st.container(border=1):
            st.subheader('📈 RTO Demand Distribution')
            mean = df_filtered_chart['demand_mwh'].mean()
            peak = df_filtered_chart['demand_mwh'].max()
            diff_day = (end_date-start_date).days

            subcol1, subcol2, subcol3 = st.columns(3)
            subcol1.metric('Average Demand (MWh)', f'{mean:.2f} MWh' if not pd.isna(mean) else 'N/A')
            subcol2.metric(f'Peak Demand over the past {diff_day} days', f'{peak}' if not pd.isna(peak) else 'N/A')
            subcol3.metric('Total Hours', f'{len(df_filtered_chart)} hrs')

            st.markdown(f'**{rto} Demand Distribution - ({start_date} to {end_date})**', text_alignment='center')
            st.line_chart(df_filtered_chart['demand_mwh'], y_label='Demand (MWh)')

        st.divider()

        metrics_all = ['mwh_ng','mwh_nuc','mwh_wnd','mwh_sun','mwh_col','mwh_wat','mwh_oil','mwh_oth']
        sum_elec_generated = sum([df_filtered_chart[col].sum() for col in metrics_all])

        # -----------------------------------------------------------------------------
        # RENEWABLE ENERGY ELECTRICITY GENERATION
        # -----------------------------------------------------------------------------
        with st.container(border=1):
            st.subheader(f'♻️ Renewable Energy Electricity Generation Distribution - ({start_date} to {end_date})')
            list_metrics_r = ['mwh_wnd','mwh_sun','mwh_wat']
            name_metrics_r = ['Wind Turbine', 'Solar Energy', 'Water']
            colors_r = ['#00E5FF', '#B026FF', '#1D4ED8']

            cols_r = st.columns(len(list_metrics_r), border=1)
            for col_r, metric_r, nm, c_r in zip(cols_r, list_metrics_r, name_metrics_r, colors_r):
                with col_r:
                    mean_r = df_filtered_chart[metric_r].mean()
                    contrib_r = round((df_filtered_chart[metric_r].sum()/sum_elec_generated)*100, 2) if not pd.isna(mean_r) else 0

                    st.markdown(f'##### **Electricity Generated By {nm}**', text_alignment='center')

                    st.metric('Average Generated', f'{mean_r:.1f} MWh' if not pd.isna(mean_r) else 'N/A')
                    st.metric('Pct. MWh Contributed', f'{contrib_r}%')
                    st.line_chart(df_filtered_chart[metric_r], color=c_r, y_label='Electricity Generated (MWh)')

        st.divider()

        # -----------------------------------------------------------------------------
        # NON-RENEWABLE ENERGY ELECTRICITY GENERATION
        # -----------------------------------------------------------------------------
        with st.container(border=1):
            st.subheader(f'♻ Non-Renewable Energy Electricity Generation Distribution - ({start_date} to {end_date})')
            list_metrics_nr = ['mwh_ng', 'mwh_col', 'mwh_oil']
            name_metrics_nr = ['Natural Gas', 'Coal', 'Oil']
            colors_nr = ['#00F5D4', '#0F766E', '#FF4B4B']

            cols_nr = st.columns(len(list_metrics_r), border=1)
            for col_nr, metric_nr, nm, c_nr in zip(cols_nr, list_metrics_nr, name_metrics_nr, colors_nr):
                with col_nr:
                    mean_nr = df_filtered_chart[metric_nr].mean()
                    contrib = round((df_filtered_chart[metric_nr].sum()/sum_elec_generated)*100, 2) if not pd.isna(mean_nr) else 0

                    st.markdown(f'##### **Electricity Generated By {nm}**', text_alignment='center')

                    st.metric('Average Generated', f'{mean_nr:.1f} MWh' if not pd.isna(mean_nr) else 'N/A')
                    st.metric('Pct. MWh Contributed', f'{contrib}%')
                    st.line_chart(df_filtered_chart[metric_nr], color=c_nr, y_label='Electricity Generated (MWh)')

        st.divider()

        lcol1, lcol2 = st.columns(2, border=1)
        with lcol1:
            # -----------------------------------------------------------------------------
            # NUCLEAR ENERGY ELECTRICITY GENERATION
            # -----------------------------------------------------------------------------
            st.markdown(f'#### **☢️ Nuclear Energy Electricity Generation**\n**({start_date} to {end_date})**', text_alignment='center')
            mean_nuc = df_filtered_chart['mwh_nuc'].mean()
            contrib_nuc = round((df_filtered_chart['mwh_nuc'].sum()/sum_elec_generated)*100, 2) if not pd.isna(mean_nuc) else 0

            ncol1, ncol2 = st.columns(2, border=1)
            ncol1.metric('Average Generated', f'{mean_nuc:.1f} MWh' if not pd.isna(mean_nuc) else 'N/A')
            ncol2.metric('Pct. MWh Contributed', f'{contrib_nuc}%')
            st.line_chart(df_filtered_chart['mwh_nuc'], color='#FF9900', y_label='Electricity Generated (MWh)')

        with lcol2:
            # -----------------------------------------------------------------------------
            # OTHER/MISCELLANEOUS ENERGY ELECTRICITY GENERATION
            # -----------------------------------------------------------------------------
            st.markdown(f'#### **💡 Electricity Generation From Other Sources**\n**({start_date} to {end_date})**', text_alignment='center')
            mean_oth = df_filtered_chart['mwh_oth'].mean()
            contrib_oth = round((df_filtered_chart['mwh_oth'].sum()/sum_elec_generated)*100, 2) if not pd.isna(mean_oth) else 0

            ncol1, ncol2 = st.columns(2, border=1)
            ncol1.metric('Average Generated', f'{mean_oth:.1f} MWh' if not pd.isna(mean_oth) else 'N/A')
            ncol2.metric('Pct. MWh Contributed', f'{contrib_oth}%')
            st.line_chart(df_filtered_chart['mwh_oth'], color='#C084FC', y_label='Electricity Generated (MWh)')